### ISSUE TITLE
Sweep: Create get books by category endpoint

### ISSUE THREAD

**Issue by mufidu** [mufidu/booku#2]
- There is a `categories` variable in `app.js` containing all categories in Book
- The endpoint should ask for a `category` parameter

<details open>
<summary>Checklist</summary>

- [X] Modify `app.js` ✓ https://github.com/mufidu/booku/commit/fed193c27d740712c8d703386394682d41b44370
- [X] Ran sandbox for `app.js`. ✓ https://github.com/mufidu/booku/commit/2409f97218164df1242632dc38956734b626eb01
- [X] Modify `test/app.test.js` ✓ https://github.com/mufidu/booku/commit/4dc09dac5d864937e1655e73f4dbc3d36947e4a8
- [X] Ran sandbox for `test/app.test.js`. ✓ https://github.com/mufidu/booku/commit/f90505804f744151acf63928a2d7ccc7b4289db4

![Flowchart](https://raw.githubusercontent.com/mufidu/booku/sweep/assets/1a8c155aab7427c6926a763a3c2e55547c287c7c9b02a4fbea9bc7cbd3c3452d_2_flowchart.svg)
</details>

**Comment by kevinlu1248** [comment]
Sorry for the bugs, can you merge this PR that fixes the sweep.yaml? https://github.com/mufidu/booku/pull/3

**Comment by mufidu** [comment]
Thanks!

**Comment by kevinlu1248** [comment]
sweep: Restart

**Comment by kevinlu1248** [comment]
sweep: Restart

**Comment by kevinlu1248** [comment]
@mufidu Looks like it was using GPT 3.5, I reset your ticket count so it uses 4 again.
